services:
  agents:
    build: ./agents
    ports:
      - "4000:4000"
    env_file:
      - ./agents/.env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/adc.json
    volumes:
      - ./secrets/adc.json:/secrets/adc.json:ro