services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
      - AGENT_URL=${AGENT_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      - PORT=${PORT}
      - HOST=${HOST}
