import pytest
from httpx import AsyncClient

@pytest.mark.asyncio
async def test_health_check(client: AsyncClient):
    response = await client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "healthy", "database": "connected"}

@pytest.mark.asyncio
async def test_root(client: AsyncClient):
    response = await client.get("/")
    assert response.status_code == 200
    assert "Welcome" in response.json()["message"]

@pytest.mark.asyncio
async def test_adk_endpoints(client: AsyncClient):
    # Verify ADK app is mounted and responding
    # ADK usually has /list-apps or /health depending on version, 
    # but let's check if the mount exists by hitting a likely 404 on the subpath, 
    # or better, the ADK docs say it exposes `list-apps`.
    # Based on get_fast_api_app source (implied), it has standard endpoints.
    # Let's try to hit the ADK web UI root or a known endpoint.
    
    response = await client.get("/adk/docs") # Docs might be auto-generated by FastAPI
    # If docs are enabled, this should be 200.
    # But let's check if we can list agents.
    # The ADK `get_fast_api_app` wraps the agent directory.
    
    # We'll just verify the health or root of ADK doesn't crash 500.
    response = await client.get("/adk/")
    # It might return 404 if no root defined, but not 500.
    assert response.status_code in [200, 404]

@pytest.mark.asyncio
async def test_auth_callback_endpoint(client: AsyncClient, mock_db_session):
    # Test the auth callback logic
    # We need to mock oauth_service.handle_google_callback
    from services.auth.oauth_service import oauth_service
    from unittest.mock import AsyncMock
    
    with pytest.MonkeyPatch.context() as m:
        m.setattr(oauth_service, "handle_google_callback", AsyncMock(return_value=True))
        
        response = await client.get("/auth/google/callback?code=123&state=456")
        assert response.status_code == 200
        assert response.json()["status"] == "success"
